---
version: "2"
secrets:
  # These files must exist for qBittorrent to run
  vpn_user:
    # Contains VPN username
    file: /host/config/vpnuser.txt
  vpn_pass:
    # Contains VPN password
    file: /host/config/vpnpass.txt

services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    env_file: .env
    volumes:
      # Media
      - /mnt/storage/data/:/data 
      # Config files, logs
      - /host/config/radarr:/config
    ports:
      # Web UI
      - 7878:7878/tcp

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    env_file: .env
    volumes:
      # Media
      - /mnt/storage/data:/data
      # Config files, logs
      - /host/config/sonarr:/config
    ports:
      # Web UI
      - 8989:8989/tcp

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    env_file: .env
    volumes:
      # Config files, logs
      - /host/config/prowlarr:/config
    ports:
      # Web UI
      - 9696:9696/tcp
 
  requestrr:
    image: darkalfx/requestrr
    container_name: requestrr
    restart: unless-stopped
    env_file: .env
    volumes:
      # Config files, logs
      - /host/config/requestrr:/root/config
    ports:
      # Web UI
      - 4545:4545/tcp

  qbittorrent:
    image: binhex/arch-qbittorrentvpn
    container_name: qbittorrentvpn
    restart: unless-stopped
    env_file: .env
    # Required for iptables permissions
    cap_add:
      - NET_ADMIN
    secrets:
      - vpn_user
      - vpn_pass
    # Use secrets for VPN_USER, VPN_PASS environment variables
    entrypoint: [ '/bin/bash', '-c', 'export VPN_USER=$$(cat /var/run/secrets/vpn_user) ; export VPN_PASS=$$(cat /var/run/secrets/vpn_pass) ; source /usr/local/bin/init.sh' ]
    environment:
     - VPN_ENABLED=yes
     - VPN_PROV=airvpn
     - VPN_CLIENT=openvpn
     - ENABLE_PRIVOXY=no
     # All host IPs for home network in CIDR notation
     # See Q4 for clarification: https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md
     - LAN_NETWORK=192.168.68.0/22
     - VPN_INPUT_PORTS=1234
     - VPN_OUTPUT_PORTS=5678
     - DEBUG=false
     - WEBUI_PORT=8080
    volumes:
      # Config files, logs
      - /host/config/qbittorrent:/config
      # Downloads
      - /mnt/storage/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      # Web UI
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      # Privoxy
      - 8118:8118

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    env_file: .env
    volumes:
      # Config files, logs
      - /host/config/sabnzbd:/config
      # Downloads
      - /mnt/storage/data/downloads:/downloads
      - /mnt/storage/data/incomplete:/incomplete-downloads
    ports:
      # Web UI
      - 9090:8080

  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    restart: unless-stopped
    # For ease of remote server availability
    network_mode: host
    env_file: .env
    environment:
      - VERSION=docker
    volumes:
      # Config files, logs
      - /host/config/plex:/config
      # Media
      - /mnt/storage/data/media:/data/media
    devices:
      # Intel QuickSync hardware transcoding
      - /dev/dri:/dev/dri
