---
version: "3"
secrets:
  # These files must exist to enable VPN access
  vpn_user:
    # Contains VPN username
    file: /host/vpnuser.txt
  vpn_pass:
    # Contains VPN password
    file: /host/vpnpass.txt

services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    env_file: .env
    volumes:
      # Media
      - /mnt/storage/data:/data 
      # Config files, logs
      - /host/radarr:/config
    ports:
      # Web UI
      - 7878:7878/tcp

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    env_file: .env
    volumes:
      # Media
      - /mnt/storage/data:/data
      # Config files, logs
      - /host/sonarr:/config
    ports:
        # Web UI
      - 8989:8989/tcp

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    env_file: .env
    volumes:
      # Config files, logs
      - /host/prowlarr:/config
    ports:
      # Prowlarr Web UI
      - 9696:9696/tcp

  requestrr:
    image: thomst08/requestrr
    container_name: requestrr
    restart: unless-stopped
    env_file: .env
    volumes:
      # Config files, logs
      - /host/requestrr:/root/config
    ports:
      # Web UI
      - 4545:4545/tcp

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    # Use VPN network
    network_mode: container:qbittorrentvpn
    depends_on:
      - qbittorrentvpn
    env_file: .env
    volumes:
      # Config files, logs
      - /host/sabnzbd:/config
      # Downloads
      - /mnt/storage/data/:/data
    # Web UI port exposed in VPN container

  # VPN Configuration: https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md
  qbittorrentvpn:
    image: binhex/arch-qbittorrentvpn
    container_name: qbittorrentvpn
    restart: unless-stopped
    env_file: .env
    # Required for iptables permissions
    cap_add:
      - NET_ADMIN
    secrets:
      - vpn_user
      - vpn_pass
    # Use secrets for VPN_USER, VPN_PASS environment variables
    entrypoint: [ '/bin/bash', '-c', 'export VPN_USER=$$(cat /var/run/secrets/vpn_user) ; export VPN_PASS=$$(cat /var/run/secrets/vpn_pass) ; source /usr/local/bin/init.sh' ]
    environment:
     - VPN_ENABLED=yes
     - VPN_PROV=airvpn
     - VPN_CLIENT=openvpn
     - ENABLE_PRIVOXY=no
     # All host IPs for home network in CIDR notation (see A4)
     - LAN_NETWORK=192.168.68.0/22
     # Web UI ports of containers routed through the VPN (see A24, A25)
     # Values: SABnzbd
     - VPN_INPUT_PORTS=8080
     # Web UI ports of containers on the LAN with which containers on the VPN need to communicate
     # (see A24, A27)
     - VPN_OUTPUT_PORTS=
     # Overridden because SABnzbd cannot be overridden from 8080 using environment variables
     - WEBUI_PORT=8090
    volumes:
      # Config files, logs
      - /host/qbittorrent:/config
      # Downloads
      - /mnt/storage/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6881:6881
      - 6881:6881/udp
      # qBittorrent Web UI
      - 8090:8090
      # Privoxy Web UI
      - 8118:8118
      # SABnzbd Web UI
      - 8091:8080

  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    restart: unless-stopped
    # Host network mode makes remote availability easier to set up
    network_mode: host
    env_file: .env
    environment:
      - VERSION=docker
    volumes:
      # Config files, logs
      - /host/plex:/config
      # Media
      - /mnt/storage/data/media:/data/media
    devices:
      # Expose graphics hardware for hardware transcoding
      - /dev/dri:/dev/dri
